from typing import TypedDict, List, Dict, Any, Optional
import operator

class AgentState(TypedDict):
    # The initial vulnerability report
    vuln_report: Dict[str, Any]
    
    # The plan generated by the Planner
    plan: List[str]
    
    # Current step index in the plan
    current_step_index: int
    
    # Execution history (logs, results)
    history: List[str]
    
    # Current status of the agent
    status: str # 'planning', 'executing', 'validating', 'done', 'failed'
    
    # Retry counter for current step
    retry_count: int
    
    # Context data (e.g., screenshot paths, extracted strings)
    context: Dict[str, Any]
