<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>3.0.0</Version>
    <Authors>Youchen Jiang</Authors>
    <Description>NativeAOT Shell Extension for Windows 11 Modern Menu</Description>
    <!-- NativeAOT for Sub-menu support -->
  </PropertyGroup>

</Project>
